# Generated by Django 2.2.12 on 2020-08-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubBanMovie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('n_star', models.IntegerField()),
                ('short', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'douban_movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('n_star', models.IntegerField()),
                ('short', models.CharField(max_length=400)),
                ('sentiment', models.FloatField()),
            ],
            options={
                'db_table': 't1',
                'managed': False,
            },
        ),
    ]
