# Generated by Django 2.2.12 on 2020-08-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DouBanMovie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
                ('n_star', models.IntegerField()),
                ('short', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'douban_movie',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DoubBanMovie',
        ),
    ]
